# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c5d40d6a8506254a77bcd94aa929628202f1a9fb3511a6becc1347b57d86a18f6c4d959d30562a779651aa0775c0932dbf081175b84aec443cff8108844c75d

test:
  secret_key_base: b9a341d44d712d7ed6dec244096ec3323680ced2741375ae8684041c070cb99820d5db069143a8cd7ca37c9b2dbf708330a0704dc0cfc60862395e5b2511bc48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
